context:
  version: 1.0.8-4

package:
  name: fish-lsp
  version: ${{ version | replace('-', '_') }}

source:
  url: https://github.com/ndonfris/fish-lsp/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 426816e99134dbd5ef0f1fba40f3ca7fdb02792711715af3f8f13b1f07f2abdf

build:
  number: 0
  script: build.sh
  skip:
    - win

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - make
    - fish
    - coreutils
    - nodejs
    - yarn
  run:
    - nodejs
    - fish

tests:
  - script:
      - npm list -g fish-lsp
      - fish-lsp --help
      - fish-lsp --version
      - "fish-lsp info | grep Version"

about:
  license: MIT
  license_file:
    - LICENSE.md
    - third-party-licenses.txt
  summary: LSP implementation for the fish shell language
  homepage: https://github.com/ndonfris/fish-lsp
  repository: https://github.com/ndonfris/fish-lsp

extra:
  recipe-maintainers:
    - danielnachun
    - anjos
