context:
  version: 1.0.8-4

package:
  name: fish-lsp
  version: ${{ version | replace('-', '_') }}

source:
  url: https://registry.npmjs.org/fish-lsp/-/fish-lsp-${{ version }}.tgz
  sha256: 5ab1efa4a3a28f97e934bf1dc7ba56347d6cbadd3817cbf3839e333108170597

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - make
    - fish
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
    - sed
  host:
    - nodejs
  run:
    - fish
    - nodejs

tests:
  - script:
     - npm list -g fish-lsp
     - fish-lsp --help
     - fish-lsp --version
     - "fish-lsp info | grep Version"
     - fish-lsp info

about:
  license: MIT
  license_file:
    - LICENSE.md
    - third-party-licenses.txt
  summary: LSP implementation for the fish shell language
  homepage: https://github.com/ndonfris/fish-lsp
  repository: https://github.com/ndonfris/fish-lsp

extra:
  recipe-maintainers:
    - anjos
    - danielnachun
