context:
  version: 6.06

package:
  name: perl-http-date
  version: ${{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/O/OA/OALDERS/HTTP-Date-${{ version }}.tar.gz
  sha256: 7b685191c6acc3e773d1fc02c95ee1f9fae94f77783175f5e78c181cc92d2b52

build:
  number: 0
  noarch: generic
  script: |
    perl Makefile.PL INSTALLDIRS=site NO_PERLLOCAL=1 NO_PACKLIST=1
    make
    make test
    make install VERBINST=1

requirements:
  build:
    - make
  host:
    - perl  # requires perl feedstock update for all versions
  run:
    - perl

tests:
  - perl:
      uses:
        - HTTP::Date

about:
  license: Artistic-1.0-Perl OR GPL-1.0-or-later
  license_file: LICENSE
  summary: HTTP::Date - date conversion routines
  homepage: http://metacpan.org/pod/HTTP::Date

extra:
  recipe-maintainers:
    - danielnachun
    - anjos
    - conda-forge/perl-packagers
