context:
  version: 0.14

package:
  name: perl-file-sharedir-install
  version: ${{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/E/ET/ETHER/File-ShareDir-Install-${{ version }}.tar.gz
  sha256: 8f9533b198f2d4a9a5288cbc7d224f7679ad05a7a8573745599789428bc5aea0

build:
  number: 0
  noarch: generic
  script: |
    perl Makefile.PL INSTALLDIRS=site NO_PERLLOCAL=1 NO_PACKLIST=1
    make
    make test
    make install VERBINST=1

requirements:
  build:
    - make
  host:
    - perl  # requires perl feedstock update for all versions
  run:
    - perl

tests:
  - perl:
      uses:
        - File::ShareDir::Install

about:
  license: Artistic-1.0 OR GPL-1.0-or-later
  license_file: LICENSE
  summary: Install shared files
  homepage: https://metacpan.org/pod/File::ShareDir::Install

extra:
  recipe-maintainers:
    - danielnachun
    - anjos
    - conda-forge/perl-packagers
