context:
  version: 1.05

package:
  name: perl-encode-locale
  version: ${{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/G/GA/GAAS/Encode-Locale-${{ version }}.tar.gz
  sha256: 176fa02771f542a4efb1dbc2a4c928e8f4391bf4078473bd6040d8f11adb0ec1

build:
  number: 0
  noarch: generic
  script: |
    perl Makefile.PL INSTALLDIRS=site NO_PERLLOCAL=1 NO_PACKLIST=1
    make
    make test
    make install VERBINST=1

requirements:
  build:
    - make
  host:
    - perl  # requires perl feedstock update for all versions
  run:
    - perl

tests:
  - perl:
      uses:
        - Encode::Locale

about:
  license: Artistic-1.0 OR GPL-1.0-or-later
  license_file: LICENSE
  summary: Determine the locale encoding
  homepage: https://metacpan.org/pod/Encode::Locale

extra:
  recipe-maintainers:
    - danielnachun
    - anjos
    - conda-forge/perl-packagers
